#!/bin/sh
#
# This file was automatically generated by the Nios II IDE Flash Programmer.
#
# It will be overwritten when the flash programmer options change.
#

cd E:/C430_Test/hello_world_0/Debug

# Creating .flash file for the FPGA configuration
"$SOPC_KIT_NIOS2/bin/sof2flash" --epcs --input="E:/C430_Test/C430_Test.sof" --output="C430_Test.flash" 

# Programming flash with the FPGA configuration
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x00000000 --sidp=0x00001910 --id=0 --timestamp=1368080176 --instance=0 "C430_Test.flash"

# Creating .flash file for the project
"$SOPC_KIT_NIOS2/bin/elf2flash" --epcs --after="C430_Test.flash" --input="hello_world_0.elf" --output="epcs.flash"

# Programming flash with the project
"$SOPC_KIT_NIOS2/bin/nios2-flash-programmer" --epcs --base=0x00000000 --sidp=0x00001910 --id=0 --timestamp=1368080176 --instance=0 "epcs.flash"

