  //Example instantiation for system 'NIOSTOP'
  NIOSTOP NIOSTOP_inst
    (
      .MISO_to_the_LAN              (MISO_to_the_LAN),
      .MOSI_from_the_LAN            (MOSI_from_the_LAN),
      .SCLK_from_the_LAN            (SCLK_from_the_LAN),
      .SS_n_from_the_LAN            (SS_n_from_the_LAN),
      .clk                          (clk),
      .data0_to_the_epcs            (data0_to_the_epcs),
      .dclk_from_the_epcs           (dclk_from_the_epcs),
      .in_port_to_the_LAN_nINT      (in_port_to_the_LAN_nINT),
      .in_port_to_the_NET_EN        (in_port_to_the_NET_EN),
      .in_port_to_the_USBSD_SEL     (in_port_to_the_USBSD_SEL),
      .in_port_to_the_USB_EN        (in_port_to_the_USB_EN),
      .in_port_to_the_USB_INT_I     (in_port_to_the_USB_INT_I),
      .in_port_to_the_USB_SDO_I     (in_port_to_the_USB_SDO_I),
      .out_port_from_the_LAN_CS     (out_port_from_the_LAN_CS),
      .out_port_from_the_LAN_RSTN   (out_port_from_the_LAN_RSTN),
      .out_port_from_the_NET_TESTDO (out_port_from_the_NET_TESTDO),
      .out_port_from_the_USBSD_RDO  (out_port_from_the_USBSD_RDO),
      .out_port_from_the_USBSD_RVLD (out_port_from_the_USBSD_RVLD),
      .out_port_from_the_USB_SCK_O  (out_port_from_the_USB_SCK_O),
      .out_port_from_the_USB_SCS_O  (out_port_from_the_USB_SCS_O),
      .out_port_from_the_USB_SDI_O  (out_port_from_the_USB_SDI_O),
      .out_port_from_the_pio_led    (out_port_from_the_pio_led),
      .reset_n                      (reset_n),
      .sce_from_the_epcs            (sce_from_the_epcs),
      .sdo_from_the_epcs            (sdo_from_the_epcs),
      .zs_addr_from_the_sdram       (zs_addr_from_the_sdram),
      .zs_ba_from_the_sdram         (zs_ba_from_the_sdram),
      .zs_cas_n_from_the_sdram      (zs_cas_n_from_the_sdram),
      .zs_cke_from_the_sdram        (zs_cke_from_the_sdram),
      .zs_cs_n_from_the_sdram       (zs_cs_n_from_the_sdram),
      .zs_dq_to_and_from_the_sdram  (zs_dq_to_and_from_the_sdram),
      .zs_dqm_from_the_sdram        (zs_dqm_from_the_sdram),
      .zs_ras_n_from_the_sdram      (zs_ras_n_from_the_sdram),
      .zs_we_n_from_the_sdram       (zs_we_n_from_the_sdram)
    );

